# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_stream.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_stream.proto\x12\x0chandtracking\"$\n\x05\x46rame\x12\x0c\n\x04left\x18\x01 \x01(\x0c\x12\r\n\x05right\x18\x02 \x01(\x0c\"\x1c\n\tStreamAck\x12\x0f\n\x07message\x18\x01 \x01(\t2J\n\x0bVideoStream\x12;\n\tSendFrame\x12\x13.handtracking.Frame\x1a\x17.handtracking.StreamAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FRAME']._serialized_start=36
  _globals['_FRAME']._serialized_end=72
  _globals['_STREAMACK']._serialized_start=74
  _globals['_STREAMACK']._serialized_end=102
  _globals['_VIDEOSTREAM']._serialized_start=104
  _globals['_VIDEOSTREAM']._serialized_end=178
# @@protoc_insertion_point(module_scope)
